theme = "tale-hugo"
languageCode = "en-us"
title = "Derek Helms"

pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[menu]
  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/derek-helms"
    weight = 0
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/dhelms1"
    weight = 0
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
