theme = "tale-hugo"
languageCode = "en-us"
title = "Derek Helms"

pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

enableEmoji = true

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/derek-helms"
    weight = 5
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/dhelms1"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/tags/projects/"
    weight = 2
  [[menu.main]]
    identifier = "exploration"
    name = "Exploration"
    title = "Exploration"
    url = "/tags/exploration/"
    weight = 3
    