baseURL = 'https://derekhelms.netlify.app/'
languageCode = 'en-us'
title = "Derek Helms"
theme = "novela"
paginate = 8


[taxonomies]
author = "authors"

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

